{% set version = "4.0.6" %}

package:
  name: pypubsub
  version: {{ version }}

source:
  url: https://github.com/schollii/pypubsub/archive/v{{ version }}.tar.gz
  sha256: 14828b4aa98bc9f341ff1ef03bbda13e8761fab515ad6d92570e986237cf9f17

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.3
    - pip
    - setuptools
  run:
    - python >=3.3

test:
  imports:
    - pubsub

about:
  license: BSD-2-Clause
  license_file: src/pubsub/LICENSE_BSD_Simple.txt
  license_family: BSD
  summary: A python publish-subscribe library
  home: https://github.com/schollii/pypubsub

extra:
  recipe-maintainers:
    - constantinpape
    - schollii
