{% set version = "4.0.3" %}

package:
  name: pypubsub
  version: {{ version }}

source:
  url: https://github.com/schollii/pypubsub/archive/v{{ version }}.tar.gz
  sha256: 0df83daa1cb0021bab858ff6812d836c9712dea59a5172be1888bb554c3a89a2
  
build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.3
    - pip
  run:
    - python >=3.3

test:
  imports:
    - pubsub

about:
  license: BSD-2-Clause
  license_file: src/pubsub/LICENSE_BSD_Simple.txt
  license_family: BSD
  summary: A python publish-subscribe library
  home: https://github.com/schollii/pypubsub

extra:
  recipe-maintainers:
    - constantinpape
    - schollii
