{% set version = "4.0.5" %}

package:
  name: pypubsub
  version: {{ version }}

source:
  url: https://github.com/schollii/pypubsub/archive/v{{ version }}.tar.gz
  sha256: 10884bf1af9e57b78a4044c9060198ff03005870a23e690e81887b6985a24f5b

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.3
    - pip
    - setuptools
  run:
    - python >=3.3

test:
  imports:
    - pubsub

about:
  license: BSD-2-Clause
  license_file: src/pubsub/LICENSE_BSD_Simple.txt
  license_family: BSD
  summary: A python publish-subscribe library
  home: https://github.com/schollii/pypubsub

extra:
  recipe-maintainers:
    - constantinpape
    - schollii
