{% set version = "4.0.7" %}

package:
  name: pypubsub
  version: {{ version }}

source:
  url: https://github.com/schollii/pypubsub/archive/v{{ version }}.tar.gz
  sha256: eb836e155fff00dba2feddece25f2ef89cf49bb5b75812f3ebeb5cd6e8c8449b

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.3
    - pip
    - setuptools
  run:
    - python >=3.3

test:
  imports:
    - pubsub

about:
  license: BSD-2-Clause
  license_file: src/pubsub/LICENSE_BSD_Simple.txt
  license_family: BSD
  summary: A python publish-subscribe library
  home: https://github.com/schollii/pypubsub

extra:
  recipe-maintainers:
    - constantinpape
    - schollii
